name: Generate and Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: |
          cd docs
          doxygen Doxyfile.in
          cd _build/html
          touch .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
