name: Run Tests and Generate Test Coverage Report

on:
  push:
    branches:
      - master

jobs:
  build_tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug .. && make test -j4
          LLVM_PROFILE_FILE="default.profraw" ./simulation/tests/test -s
          if [ $? -ne 0 ]; then
            exit 1
          fi

      - name: Generate Test Coverage Report
        run: |
          xcrun llvm-profdata merge -sparse default.profraw -o default.profdata
          xcrun llvm-cov report ./simulation/tests/test -instr-profile=default.profdata

